name: Build Expo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS login check (opcional)
        run: eas whoami || true

      - name: Run EAS build
        env:
          EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform android --profile production --non-interactive
